language: java

notifications:
  irc: "chat.freenode.net#jsense"
  email: false

before_install:
  - echo 'yes' | sudo add-apt-repository ppa:chris-lea/protobuf
  - sudo apt-get update -qq
  - sudo apt-get install -qq protobuf-compiler
