language: java

notifications:
  irc: "chat.freenode.net#jsense"
  email: false

env:
  - TERM=dumb

before_install:
  - sudo apt-get update
  - sudo apt-get install protobuf-compiler libprotobuf-dev

install:
  - ./gradlew assemble -s

script:
  - ./gradlew check -s
