language: java

notifications:
  irc: "chat.freenode.net#jsense"
  email: false

env:
  - TERM=dumb

before_install:
  - echo 'yes' | sudo add-apt-repository ppa:chris-lea/protobuf
  - sudo apt-get update
  - sudo apt-get install protobuf-compiler
  - cat /etc/ld.so.conf
  - cat /etc/ld.so.conf.d/*.conf
  - sudo find / -name libprotobuf.so.*
  - sudo ldconfig

install:
  - ./gradlew assemble -s

script:
  - ./gradlew check -s
