// CHECKSTYLE:OFF
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_model.proto

package org.jsense.serialize.protobuf;

public final class ProtoModel {
  private ProtoModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ThreeAxisSensorEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 absolute_timestamp = 1;
    /**
     * <code>optional int64 absolute_timestamp = 1;</code>
     */
    boolean hasAbsoluteTimestamp();
    /**
     * <code>optional int64 absolute_timestamp = 1;</code>
     */
    long getAbsoluteTimestamp();

    // optional int64 relative_timestamp = 2;
    /**
     * <code>optional int64 relative_timestamp = 2;</code>
     */
    boolean hasRelativeTimestamp();
    /**
     * <code>optional int64 relative_timestamp = 2;</code>
     */
    long getRelativeTimestamp();

    // optional float x = 3;
    /**
     * <code>optional float x = 3;</code>
     */
    boolean hasX();
    /**
     * <code>optional float x = 3;</code>
     */
    float getX();

    // optional float y = 4;
    /**
     * <code>optional float y = 4;</code>
     */
    boolean hasY();
    /**
     * <code>optional float y = 4;</code>
     */
    float getY();

    // optional float z = 5;
    /**
     * <code>optional float z = 5;</code>
     */
    boolean hasZ();
    /**
     * <code>optional float z = 5;</code>
     */
    float getZ();
  }
  /**
   * Protobuf type {@code org.jsense.serialize.protobuf.ThreeAxisSensorEvent}
   */
  public static final class ThreeAxisSensorEvent extends
      com.google.protobuf.GeneratedMessage
      implements ThreeAxisSensorEventOrBuilder {
    // Use ThreeAxisSensorEvent.newBuilder() to construct.
    private ThreeAxisSensorEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ThreeAxisSensorEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ThreeAxisSensorEvent defaultInstance;
    public static ThreeAxisSensorEvent getDefaultInstance() {
      return defaultInstance;
    }

    public ThreeAxisSensorEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ThreeAxisSensorEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              absoluteTimestamp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              relativeTimestamp_ = input.readInt64();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              x_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              y_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              z_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jsense.serialize.protobuf.ProtoModel.internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jsense.serialize.protobuf.ProtoModel.internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent.class, org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<ThreeAxisSensorEvent> PARSER =
        new com.google.protobuf.AbstractParser<ThreeAxisSensorEvent>() {
      public ThreeAxisSensorEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ThreeAxisSensorEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ThreeAxisSensorEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 absolute_timestamp = 1;
    public static final int ABSOLUTE_TIMESTAMP_FIELD_NUMBER = 1;
    private long absoluteTimestamp_;
    /**
     * <code>optional int64 absolute_timestamp = 1;</code>
     */
    public boolean hasAbsoluteTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 absolute_timestamp = 1;</code>
     */
    public long getAbsoluteTimestamp() {
      return absoluteTimestamp_;
    }

    // optional int64 relative_timestamp = 2;
    public static final int RELATIVE_TIMESTAMP_FIELD_NUMBER = 2;
    private long relativeTimestamp_;
    /**
     * <code>optional int64 relative_timestamp = 2;</code>
     */
    public boolean hasRelativeTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 relative_timestamp = 2;</code>
     */
    public long getRelativeTimestamp() {
      return relativeTimestamp_;
    }

    // optional float x = 3;
    public static final int X_FIELD_NUMBER = 3;
    private float x_;
    /**
     * <code>optional float x = 3;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float x = 3;</code>
     */
    public float getX() {
      return x_;
    }

    // optional float y = 4;
    public static final int Y_FIELD_NUMBER = 4;
    private float y_;
    /**
     * <code>optional float y = 4;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float y = 4;</code>
     */
    public float getY() {
      return y_;
    }

    // optional float z = 5;
    public static final int Z_FIELD_NUMBER = 5;
    private float z_;
    /**
     * <code>optional float z = 5;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float z = 5;</code>
     */
    public float getZ() {
      return z_;
    }

    private void initFields() {
      absoluteTimestamp_ = 0L;
      relativeTimestamp_ = 0L;
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, absoluteTimestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, relativeTimestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, absoluteTimestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, relativeTimestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.jsense.serialize.protobuf.ThreeAxisSensorEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jsense.serialize.protobuf.ProtoModel.internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jsense.serialize.protobuf.ProtoModel.internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent.class, org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent.Builder.class);
      }

      // Construct using org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        absoluteTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        relativeTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jsense.serialize.protobuf.ProtoModel.internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_descriptor;
      }

      public org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent getDefaultInstanceForType() {
        return org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent.getDefaultInstance();
      }

      public org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent build() {
        org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent buildPartial() {
        org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent result = new org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.absoluteTimestamp_ = absoluteTimestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.relativeTimestamp_ = relativeTimestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent) {
          return mergeFrom((org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent other) {
        if (other == org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent.getDefaultInstance()) return this;
        if (other.hasAbsoluteTimestamp()) {
          setAbsoluteTimestamp(other.getAbsoluteTimestamp());
        }
        if (other.hasRelativeTimestamp()) {
          setRelativeTimestamp(other.getRelativeTimestamp());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jsense.serialize.protobuf.ProtoModel.ThreeAxisSensorEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 absolute_timestamp = 1;
      private long absoluteTimestamp_ ;
      /**
       * <code>optional int64 absolute_timestamp = 1;</code>
       */
      public boolean hasAbsoluteTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 absolute_timestamp = 1;</code>
       */
      public long getAbsoluteTimestamp() {
        return absoluteTimestamp_;
      }
      /**
       * <code>optional int64 absolute_timestamp = 1;</code>
       */
      public Builder setAbsoluteTimestamp(long value) {
        bitField0_ |= 0x00000001;
        absoluteTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 absolute_timestamp = 1;</code>
       */
      public Builder clearAbsoluteTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        absoluteTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 relative_timestamp = 2;
      private long relativeTimestamp_ ;
      /**
       * <code>optional int64 relative_timestamp = 2;</code>
       */
      public boolean hasRelativeTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 relative_timestamp = 2;</code>
       */
      public long getRelativeTimestamp() {
        return relativeTimestamp_;
      }
      /**
       * <code>optional int64 relative_timestamp = 2;</code>
       */
      public Builder setRelativeTimestamp(long value) {
        bitField0_ |= 0x00000002;
        relativeTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 relative_timestamp = 2;</code>
       */
      public Builder clearRelativeTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        relativeTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional float x = 3;
      private float x_ ;
      /**
       * <code>optional float x = 3;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float x = 3;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>optional float x = 3;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000004;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float x = 3;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0F;
        onChanged();
        return this;
      }

      // optional float y = 4;
      private float y_ ;
      /**
       * <code>optional float y = 4;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float y = 4;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>optional float y = 4;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000008;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float y = 4;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y_ = 0F;
        onChanged();
        return this;
      }

      // optional float z = 5;
      private float z_ ;
      /**
       * <code>optional float z = 5;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float z = 5;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>optional float z = 5;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000010;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float z = 5;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000010);
        z_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.jsense.serialize.protobuf.ThreeAxisSensorEvent)
    }

    static {
      defaultInstance = new ThreeAxisSensorEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.jsense.serialize.protobuf.ThreeAxisSensorEvent)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto_model.proto\022\035org.jsense.serializ" +
      "e.protobuf\"o\n\024ThreeAxisSensorEvent\022\032\n\022ab" +
      "solute_timestamp\030\001 \001(\003\022\032\n\022relative_times" +
      "tamp\030\002 \001(\003\022\t\n\001x\030\003 \001(\002\022\t\n\001y\030\004 \001(\002\022\t\n\001z\030\005 " +
      "\001(\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jsense_serialize_protobuf_ThreeAxisSensorEvent_descriptor,
              new java.lang.String[] { "AbsoluteTimestamp", "RelativeTimestamp", "X", "Y", "Z", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
